<h2 align="center">Data Preprocessing: One Hot Encoding<h2>

In [2]:
import pandas as pd

df = pd.read_csv("home_prices.csv")
df

         locality  area_sqr_ft  price_lakhs  bedrooms
0          Kollur          656         39.0         2
1          Kollur         1260         83.2         2
2          Kollur         1057         86.6         3
3          Kollur         1259         59.0         2
4          Kollur         1800        140.0         3
5          Kollur         1325         80.1         2
6          Kollur         1085        116.0         3
7          Kollur         1110         45.0         2
8          Kollur         1700        100.0         3
9   Banjara Hills         1650        200.0         3
10  Banjara Hills         2438        316.0         3
11  Banjara Hills         2115        220.0         2
12  Banjara Hills         1600        150.0         3
13  Banjara Hills         2400        300.0         3
14  Banjara Hills         1100         85.0         2
15  Banjara Hills         2600        400.0         3
16        Mankhal         1100         54.0         2
17        Mankhal         1125         64.0         2
18        Mankhal         1008         50.0         2
19        Mankhal         1266         78.0         2
20        Mankhal         1540         94.0         3
21        Mankhal         1200         85.0         3

In [61]:
pd.get_dummies(df, columns = ["locality"]) ## creating dummy columns

,area_sqr_ft,price_lakhs,bedrooms,locality_Banjara Hills,locality_Kollur,locality_Mankhal
0,656,39.0,2,False,True,False
1,1260,83.2,2,False,True,False
2,1057,86.6,3,False,True,False
3,1259,59.0,2,False,True,False
4,1800,140.0,3,False,True,False
5,1325,80.1,2,False,True,False
6,1085,116.0,3,False,True,False
7,1110,45.0,2,False,True,False
8,1700,100.0,3,False,True,False
9,1650,200.0,3,True,False,False
10,2438,316.0,3,True,False,False
11,2115,220.0,2,True,False,False
12,1600,150.0,3,True,False,False
13,2400,300.0,3,True,False,False
14,1100,85.0,2,True,False,False
15,2600,400.0,3,True,False,False
16,1100,54.0,2,False,False,True
17,1125,64.0,2,False,False,True
18,1008,50.0,2,False,False,True
19,1266,78.0,2,False,False,True
20,1540,94.0,3,False,False,True
21,1200,85.0,3,False,False,True

In [63]:
df_encoded = pd.get_dummies(df, columns = ["locality"], drop_first = True) ## dropping a redundant column

In [65]:
df_encoded.sample(5)

    area_sqr_ft  price_lakhs  bedrooms  locality_Kollur  locality_Mankhal
6          1085        116.0         3             True             False
14         1100         85.0         2            False             False
8          1700        100.0         3             True             False
3          1259         59.0         2             True             False
21         1200         85.0         3            False              True

In [67]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X = df_encoded.drop('price_lakhs', axis = 1)
y = df_encoded['price_lakhs']

#train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

#Building the model

model = LinearRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8558905263155381

In [69]:
test = pd.DataFrame([
    {"area_sqr_ft" : 1600, "bedrooms" : 2, "locality_Kollur" : False, "locality_Mankhal": False},
    {"area_sqr_ft" : 1600, "bedrooms" : 2, "locality_Kollur" : True, "locality_Mankhal": False},
    {"area_sqr_ft" : 1600, "bedrooms" : 2, "locality_Kollur" : False, "locality_Mankhal": True}
])

model.predict(test)

array([157.03383393, 113.96340695, 109.25104283])