## L1, L2 Regularization </h1>

In [4]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("dataset.csv")
df.head(3)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f142,f143,f144,f145,f146,f147,f148,f149,f150,target
0,-0.924357,-0.326536,-1.875007,-1.780626,-0.630143,0.788204,2.792209,-0.772192,-0.450994,0.400000,...,0.968645,-0.702053,-0.327662,-0.392108,-1.463515,0.296120,0.261055,0.005113,-0.234587,10.681366
1,0.001795,-1.285599,-0.726774,0.385711,0.891863,0.599451,-0.140553,-0.761760,0.117707,0.333231,...,0.856399,0.214094,-1.245739,0.173181,0.385317,-0.883857,0.153725,0.058209,-1.142970,-60.163343
2,0.956702,2.319330,-0.705012,0.081829,0.330880,0.838491,2.493000,1.227669,-0.785989,-0.920674,...,-0.493001,-0.589365,0.849602,0.357015,-0.692910,0.899600,0.307300,0.812862,0.629629,131.226545

In [6]:
X = df.drop(['target'], axis = 1)
y = df['target']

In [7]:
X.sample(5)

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f141,f142,f143,f144,f145,f146,f147,f148,f149,f150
126,0.837764,-0.667189,0.686354,0.637325,-0.215961,1.389024,0.128617,-1.092142,-0.679231,-0.512374,...,-0.405011,0.129422,-0.353120,0.030849,-0.683381,1.108674,1.423265,-0.133390,-1.386489,-0.523843
9,-0.605715,-0.669073,-1.478912,-0.365322,-1.170113,0.136535,-0.677715,-0.576510,0.742095,-0.973069,...,0.208383,-2.041735,-0.247177,-0.681984,-1.001620,-0.281100,1.797687,0.640843,-0.571179,0.572583
156,-1.422975,-1.176173,0.654976,1.608781,-1.388543,-1.371743,-0.709789,-0.892788,-0.970124,0.097670,...,0.783731,-1.398098,-0.244400,0.555858,-0.287584,-0.206754,-0.137786,-0.835601,1.173901,-1.018038
88,0.712482,-0.160074,-0.641165,-1.989946,1.453840,-1.330226,-0.016054,0.831499,1.031381,-0.850975,...,-0.302269,0.530867,-0.935831,-1.075894,-1.123195,2.045655,0.530343,0.304492,-1.057515,0.623342
137,0.287124,-1.090399,-1.581191,0.159856,1.901191,0.092845,-1.881849,-1.803140,-0.612437,0.896839,...,-0.820839,0.440757,0.906343,0.210635,-0.801220,0.456203,-0.402049,0.745187,1.483259,-2.605577

In [8]:
y.sample(5)

93      28.400494
140    163.718330
63      25.105191
55     -20.193763
33     -14.503634
Name: target, dtype: float64

### Training using Simple linear regression

In [10]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)
model = LinearRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.7407699448090973

### Training using Lasso regression

In [27]:
lasso_model = Lasso(alpha = 1.0) # Lasso = linear regression with MSE loss + L1 regularization (drives some coefficients to zero)
lasso_model.fit(X_train, y_train)
lasso_model.score(X_test, y_test)

0.9901476660336155

### Training using Ridge regression

In [30]:
ridge_model = Ridge(alpha = 1.0) # Ridge  = linear regression with MSE loss + L2 regularization (shrinks coefficients but doesn’t make them zero)
ridge_model.fit(X_train, y_train)
ridge_model.score(X_test, y_test)

0.9462671341742038

We see a significant improvement in perforance when we use ridge and lasso regression