In [1]:
import pandas as pd  

## URL to the Auto MPG dataset 
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"

## Column names based on the dataset description
column_names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name']

## Note: The dataset uses various delimiters and contains missing values denoted as '?'
df = pd.read_csv(url, delim_whitespace=True, names=column_names, na_values='?', comment='\t')

## Display few rows of the dataframe
df.sample(5)

C:\Users\Asus\AppData\Local\Temp\ipykernel_11348\308186892.py:10: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(url, delim_whitespace=True, names=column_names, na_values='?', comment='\t')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
150,26.0,4,108.0,93.0,2391.0,15.5,74,3,subaru
387,38.0,6,262.0,85.0,3015.0,17.0,82,1,oldsmobile cutlass ciera (diesel)
165,20.0,8,262.0,110.0,3221.0,13.5,75,1,chevrolet monza 2+2
283,20.2,6,232.0,90.0,3265.0,18.2,79,1,amc concord dl 6
75,14.0,8,318.0,150.0,4077.0,14.0,72,1,plymouth satellite custom (sw)

In [2]:
df.isna().sum() ## Checking Missing Values

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [3]:
df.horsepower.describe()  ## Descriptive Statistics

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [4]:
value = df.horsepower.mean()
df.horsepower.fillna(value, inplace = True) ### 4. Handling Missing Data : Filling missing values in the 'horsepower' column with its mean value.

C:\Users\Asus\AppData\Local\Temp\ipykernel_11348\3431682670.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.horsepower.fillna(value, inplace = True) ### 4. Handling Missing Data : Filling missing values in the 'horsepower' column with its mean value.

In [5]:
df.isna().sum() ## Verifying Missing Value Handling

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [6]:
features = ['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin']

X = df[features] # standard convention -> X is capital as it has multiple columns
y = df['mpg'] # y is small as it has only one column

X.head()

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504.0,12.0,70,1
1,8,350.0,165.0,3693.0,11.5,70,1
2,8,318.0,150.0,3436.0,11.0,70,1
3,8,304.0,150.0,3433.0,12.0,70,1
4,8,302.0,140.0,3449.0,10.5,70,1

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42) ## 20% test and 80% in training

In [9]:
df.shape,X_train.shape, X_test.shape, y_train.shape, y_test.shape

((398, 9), (318, 7), (80, 7), (318,), (80,))

In [10]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = model.predict(X_test)
y_pred[:5]

array([32.86345735, 29.58130242, 21.35126058, 16.80568721, 12.50136229])

In [12]:
y_test[:5] ## when value was 33 it predicted 32.86 and so on...it's doing a close match

198    33.0
396    28.0
33     19.0
208    13.0
93     14.0
Name: mpg, dtype: float64

In [13]:
## to actually measure it we can use

In [14]:
## 1. MSE

In [15]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print(mse, mae)

8.19545210407378 2.25338840593176

In [16]:
## 2. R2 score -> easy to interpret

In [17]:
r2_score(y_test, y_pred)

0.8475731044779435

In [18]:
model.score(X_test, y_test) ## internally its the same thing [It takes X_test and generates y_pred]

0.8475731044779435